name: Quacksurvey server Deploy
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "./package-lock.json"
      - name: Deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          passphrase: ${{ secrets.SSH_PEM_PASSPHRASE }}
          source: "./*"
          target: ${{ secrets.SERVER_PATH }}
      - name: Install Package
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_NAME }}
          key: ${{ secrets.SSH_PEM_KEY }}
          passphrase: ${{ secrets.SSH_PEM_PASSPHRASE }}
          script_stop: true
          script: |
            cd ${{ secrets.SERVER_PATH }}
            npm install
